Repository clintonjosephs/book-a-doctor-backend, pull requests merged in 2022-06, with the labels that each got.

#17 Doctors show
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/concerns/record_not_found.rb
  app/controllers/v1/doctors_controller.rb
  spec/integration/doctors_spec.rb
  spec/requests/v1/doctors_spec.rb
Labels: enhancement

#19 Add jsonapi-serializer for user and doctor, create seed data with images
  Gemfile
  Gemfile.lock
  app/controllers/v1/doctors_controller.rb
  app/controllers/v1/users_controller.rb
  app/models/doctor.rb
  app/models/user.rb
  app/serializers/doctor_serializer.rb
  app/serializers/user_serializer.rb
  config/environments/development.rb
  config/initializers/cors.rb
  db/seeds.rb
  public/doctors/doctor1.jpg
  public/doctors/doctor2.jpg
  public/doctors/doctor3.jpg
  public/users/194934.png
  public/users/194935.png
  public/users/194938.png
Labels: group task

#39 Fix integration test for deleting doctor
  Gemfile.lock
  spec/integration/doctors_spec.rb
Labels: invalid

#41 Final Changes merge to main branch
  Gemfile.lock
  README.md
  spec/integration/appointments_spec.rb
  spec/integration/doctors_spec.rb
  spec/support/request_spec_helper.rb
  swagger/v1/swagger.yaml
Labels: bug, documentation, enhancement
